spring:
  profiles:
    active: dev

logging:
  level:
    org.springframework: ERROR
    org.hibernate: ERROR
    org.springframework.boot.autoconfigure.security: DEBUG
  file: C:\Users\teobo_000\Documents\agenda\server.log
